### ISSUE TITLE
seeking help to add support for sidekiq worker

### ISSUE THREAD

**Issue by nipendar** [kares/jruby-rack-worker#17]
Hi @kares 

Thanks for this very useful gem. I am currently using Resque worker in production & it is giving me a hard time in terms of CPU consumption. I badly need to switch to Sidekiq, could you please guide me on how to add sidekiq worker to jruby-rack-worker, I know this is not supported by default & you did write a section on custom workers, but I am not really able to pull it off.

**Comment by kares** [comment]
sorry I do not have time to look into other people's use cases (for "free") esp. when there's little effort ...

**Comment by liuweijack** [comment]
https://github.com/liuweijack/jruby-rack-worker

**Comment by kares** [comment]
@liuweijack thank you ... hopefully will find some time to review. seems a decent start, does it roll?
e.g. there seems to be `trap`-ing code still happening, no configuration seems handled and I'm not sure but some Sidekiq client API parts probably assumes running standalone (won't work in multi-deploy envs) ...

**Comment by liuweijack** [comment]
@kares thank you for your comment.It seems work by now.Sidekiq will using config/sidekiq.yml as configuration file ,no problem with custom configuration(but not all option  was tested)

**Comment by dimitertodorov** [comment]
@liuweijack Do you still have this code available?
Looking to bootstrap my sidekiq into TOMCAT if possible.
